### ISSUE TITLE
auth/authorize login redirect not working

### ISSUE THREAD

**Issue by d-sko** [Josh-Star/AniList-API-Docs#10]
Hi,

the documentation says if the user is not logged in when opening auth/authorize he will be redirected to login. But it looks like this is not working, the server returns a 500 error code.

**Comment by Josh-Star** [comment]
Should be fixed now.

**Comment by RainerZA** [comment]
Still not working for me

**Comment by matt4682** [comment]
@RainerZA Does it work for you if the user is already logged in? I have tried it both with an already logged in user and with no logged in user and both appear to redirect fine for me.

I tried with both authorization pin and authorization code.

**Comment by RainerZA** [comment]
works if the user is already logged in, but if not I get 500
