### ISSUE TITLE
Provide PIN-based authorization

### ISSUE THREAD

**Issue by z411** [Josh-Star/AniList-API-Docs#11]
Right now the OAuth implementation seems to be heavily web-oriented; to develop a desktop application one would have to use a third-party server to return the code, like anihilist does. Is it possible to have PIN-based authorization (similar to Twitter's implementation) to potentially avoid such a workaround?

**Comment by Josh-Star** [comment]
Pin authorization grant type is now available :)

**Comment by z411** [comment]
Thank you very much!
