### ISSUE TITLE
Detailed anime/manga lists

### ISSUE THREAD

**Issue by matt4682** [Josh-Star/AniList-API-Docs#14]
Is it possible for the API to offer an API call for anime and manga lists that contains full-sized anime/manga models instead of the small models?

**Comment by Josh-Star** [comment]
What reason do you have for wanting the full model versions?
I was thinking about adding the airing data to the lists but not too sure about the full model.

**Comment by matt4682** [comment]
I have a particular interest in the synonyms list. 
Essentially I am trying to match filenames to certain anime and the filename frequenly matches up with a synonym rather than one of the three titles.

**Comment by Josh-Star** [comment]
I do imagine synonyms will be requested quite a bit for the same reason as yours so I've added them to the small data model. For other thing you'll have to make an additional api call.

**Comment by matt4682** [comment]
Awesome, thanks!
