### ISSUE TITLE
Username for requests

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#15]
Hi,

I saw that we need to use "user/{id || displayname}/animelist" for requesting the animelist. My only problem is how I should do this because I do not know the username of the users which is logged in.

The Oauth method is using the browser so I basically can't know what the username is. Is there a way to know the username?

**Comment by Josh-Star** [comment]
Just do a get to /user, that will return the basic model of the current authenticated user. 
[Docs](http://anilist-api.readthedocs.org/en/latest/user.html#basic)
