### ISSUE TITLE
Star score type doesn't return a string.

### ISSUE THREAD

**Issue by matt4682** [Josh-Star/AniList-API-Docs#16]
The API has the star score type labelled as returning a string type but it's returning integers from 1-5.

 ![API](http://i.imgur.com/AzHq9T3.png)

For example a current user receives [this](http://hastebin.com/tapaluraqe) JSON response. Note `"score_type": 2,` on line 14.
 And the user list returned is [this](http://hastebin.com/merayoruyo). Note `"score": 2,` on line 13

**Comment by Josh-Star** [comment]
Ah sorry about that, the docs are incorrect there. Star type should return 0-5 int.
