### ISSUE TITLE
authorize bug & typo

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#17]
according to the documentation:
"This will direct the resource owner to a web page where they may choose to accept or deny the client."

I am already logged in on my phone but AniList persists to go at the home page and not the approval page. This is probably a bug with authorize on mobile devices. (I compared it with my desktop browser and it is really mobile only).

I also found a typo: "acecpt" in the approval page.

**Comment by Josh-Star** [comment]
Thanks, I'll look into this.

**Comment by ratan12** [comment]
I was using the chrome browser, anyway I switched to the webview inside the app and the problem went away.

**Comment by Josh-Star** [comment]
Huh thats odd. Maybe its just an issue with andriod chrome, webview uses the default andriod browser right? Do you know what version you have of that? Thanks

**Comment by ratan12** [comment]
Chrome 39.0.2171.93
Default internet 4.4.4-7392

Yes the webview is using the default internet app.
