### ISSUE TITLE
advanced_rating is boolean instead of int?

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#18]
java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 1 column 525 path $.advanced_rating

""advanced_rating": 1,"
I see an int in the documentation but apparently it is a boolean?

**Comment by Josh-Star** [comment]
Oops yes advanced_rating is in fact a boolean, not an int. Sorry, I'll fix the docs for that now.
