### ISSUE TITLE
AniDB ids

### ISSUE THREAD

**Issue by steino** [Josh-Star/AniList-API-Docs#19]
Any possiblities of adding and exposing AniDB id's for animes? Media center software like XBMC and Plex both use scrapers based on AniDB and it would make matching shows when updating via the API a lot easier.

**Comment by Josh-Star** [comment]
I'm afraid we won't be supporting this for the same reasons as not providing mal ids #13. 
We also have absolutely no tracking of AniDB ids compared to AniList's, not sure if we ever really plan to, so its not something we actually provide at the moment even if we wanted to.
