### ISSUE TITLE
High response time querying user anime list

### ISSUE THREAD

**Issue by blitzprog** [Josh-Star/AniList-API-Docs#20]
Standard jQuery JSON request to retrieve the anime list:

![](http://puu.sh/exTLZ/013fb55654.png)

![](http://puu.sh/ezBM3/ce733b76ce.png)

Data is taken from test runs of the new [Anime Release Notifier](https://github.com/blitzprog/anime-release-notifier/). In my tests the average was:

Hummingbird (JSON): 0.3 s
MAL (HTML): 0.5 s
Anilist (JSON): 2.1 s

**Comment by Josh-Star** [comment]
I assumed this was something to do with the large amount to of oauth session you have, causing some stupidity long sql query. But even using your client access token's I cannot replicate any response times longer then 400ms, I have no speed issues using the new anime release notifier version either. 

Have any of your users complained about the long anilist load times? Are your load times slow just for the API or also for the normal AniList site too? 

Any chance you could test this on a different machine & network? Just to make sure it is something wrong on my end. Thanks

**Comment by blitzprog** [comment]
I see. The API requests on the website are slow as well.

![Anilist Website](http://puu.sh/eEbhP/cf29047930.png)

Users didn't complain about loading times (doesn't mean they don't exist).
The relevant code is in line 30, it's just jQuery getJSON:
https://github.com/blitzprog/anime-release-notifier/blob/master/js/list-providers/anilist.co.js

I think we can agree that the code can not be the root of the problem.
Indeed the network seems to be the number 1 suspect. I already am on a different machine than yesterday but on the same network. I'll ask a tech-savy friend in Germany to record the request time.

**Comment by blitzprog** [comment]
I got the data, the latency from Germany is much lower:

![Anilist Germany](http://puu.sh/eEeef/524ad1ced9.png)

This is really strange since my ping to anilist is very low and all requests _except_ for this animelist API request are fast.

**Comment by Josh-Star** [comment]
I'll close this now as I assume you aren't working with the AniList API anymore and I haven't heard any more reports of this.
