### ISSUE TITLE
Refresh token expiration

### ISSUE THREAD

**Issue by asermax** [Josh-Star/AniList-API-Docs#21]
I'm currently having an issue while using the API and trying to refresh the access token by using the refresh token. It seems to work okay for a while, but sometimes it fails with the following error:

```
400 Client Error: Bad Request - {"error":"invalid_request","error_description":"The refresh token is invalid."}
``` 

It may be an error on our part, but I find it weird that it works correctly for a while before failing.
So I was wondering, does the refresh token have an expiration time or something of the like? Does the refresh tokens get wiped for some reason?

In any case, this is pretty inconvenient because it forces our users to reauthorize the app every few days; is there some way to work around it?

Thanks in advance.

**Comment by ratan12** [comment]
AniList API is using OAuth 2.

According the documentation: "For security this access token will expire in 1 hour".

AniList is providing a refresh token which you can use to request a new access token.
According the documentation: "We don’t want the resource owner to re-accept the client every time the access token becomes invalid, so we use the the refresh token to request a new one"

**Comment by asermax** [comment]
Hi there @ratan12. I think you didn't fully understand the issue at hand.

We _are_ using the refresh token to get a new access token when it expires, the issue we are facing is that sometimes the refresh process fails with the error I mentioned above.
Nowhere in the documentation it mentions tha the _refresh token_ expires, that's why I opened up this issue to clarify that matter/find where did the process go wrong.

**Comment by ratan12** [comment]
@asermax Sorry I thought you meant the acces token.

I am just an other app dev but the refresh token is working fine in my case. I could give you an advice to check the raw output of the API with the refresh token and log which refresh token your program is using to make the request.

It is possible that something goes wrong with saving or processing the refresh token.

**Comment by asermax** [comment]
Alright, I will give that a go, thanks.

**Comment by Josh-Star** [comment]
Is this still an issue for you? or did you find it was something going wrong client-side?

**Comment by asermax** [comment]
We haven't encountered the issue again since last time and the logs show
normal behavior (the correct refresh token is being used on the request and
the received access token is valid).
Still, it happened twice before (the API handling code hasn't changed since
the first time) and to various users simultaneously, so I would like to
wait a bit before closing the issue.

Just in case, I believe the first time it happened it was about the same
time you deployed some fixes to the API, could it be related in some way?

**Comment by Josh-Star** [comment]
Okay yeah I think it was probably related to some changes I made to the API token data, that shouldn't happen again so I'll close this for now.

**Comment by asermax** [comment]
Just happened again, here's an extract of the log for a particular user:

```
DEBUG 2015-01-23 05:33:37,310 anilist Calling api: https://anilist.co/api/animelist, {'data': {'list_status': 'watching', 'episodes_watched': 3, 'id': 20793}, 'headers': {'Authorization': 'Bearer A4E3aBQwRHJt4GcJpqoifCeLSEdfgwAYVvIM5QPF'}}
DEBUG 2015-01-23 05:33:37,850 anilist Response: {"list_status":"watching","score":null,"priorty":null,"rewatched":null,"notes":null,"private":null,"added_time":"2015-01-04 05:13:08","episodes_watched":3,"chapters_read":null,"volumes_read":null,"hidden_default":null,"custom_lists":[null,null,null,null,null]}
DEBUG 2015-01-23 05:55:30,568 anilist Calling api: https://anilist.co/api/animelist, {'data': {'list_status': 'watching', 'episodes_watched': 14, 'id': 20665}, 'headers': {'Authorization': 'Bearer A4E3aBQwRHJt4GcJpqoifCeLSEdfgwAYVvIM5QPF'}}
DEBUG 2015-01-23 05:55:31,037 anilist Response: {"list_status":"watching","score":0,"priorty":null,"rewatched":null,"notes":null,"private":null,"added_time":"2014-12-29 06:06:55","episodes_watched":14,"chapters_read":null,"volumes_read":null,"hidden_default":null,"custom_lists":[null,null,null,null,null]}
DEBUG 2015-01-23 06:28:31,619 anilist Calling api: https://anilist.co/api/auth/access_token, {'params': {'refresh_token': 'Apt8ACChExTs8mrR8gMN7D8rMFiUmGaDM6hKosGO', 'grant_type': 'refresh_token', 'client_id': 'xxxxxxxxxx', 'client_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}}
DEBUG 2015-01-23 06:28:33,637 anilist Response: {"access_token":"jtEIid13zSvV2Ea9RWPaRmMa5pZ8bkATwtpEocGH","token_type":"bearer","expires":1421998078,"expires_in":3600}
DEBUG 2015-01-23 06:28:33,640 anilist Calling api: https://anilist.co/api/animelist, {'data': {'list_status': 'watching', 'episodes_watched': 15, 'id': 20623}, 'headers': {'Authorization': 'Bearer jtEIid13zSvV2Ea9RWPaRmMa5pZ8bkATwtpEocGH'}}
DEBUG 2015-01-23 06:28:33,995 anilist Response: {"list_status":"watching","score":0,"priorty":null,"rewatched":null,"notes":null,"private":null,"added_time":"2014-12-29 06:06:55","episodes_watched":15,"chapters_read":null,"volumes_read":null,"hidden_default":null,"custom_lists":[null,null,null,null,null]}
DEBUG 2015-01-24 22:52:21,783 anilist Calling api: https://anilist.co/api/auth/access_token, {'params': {'refresh_token': 'Apt8ACChExTs8mrR8gMN7D8rMFiUmGaDM6hKosGO', 'grant_type': 'refresh_token', 'client_id': 'xxxxxxxxxx', 'client_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}}
DEBUG 2015-01-24 22:52:22,322 anilist Response: {"error":"invalid_request","error_description":"The refresh token is invalid."}
```

Before the first line there were a bunch of other instances of the token refresh process working correctly, and as seen on the log, the parameters seem to be correct.
Let me know if you need more info or if you see something clearly wrong in the logs :P

**Comment by Josh-Star** [comment]
Do you receive the same response error if you try the same access_token token request again? Or does requesting the access token work fine with another try.

**Comment by asermax** [comment]
Just tried, it seems to return the same error.

**Comment by asermax** [comment]
The error recurred once more, for a different user:

```
DEBUG 2015-01-23 04:32:56,782 anilist Calling api: https://anilist.co/api/animelist, {'data': {'list_status': 'watching', 'episodes_watched': 12, 'id': 20665}, 'headers': {'Authorization': 'Bearer rtAFj4R7nA6iS8CtAmmY0phkAeQDM0kBQZ5rDvQh'}}
DEBUG 2015-01-23 04:32:57,457 anilist Response: {"list_status":"watching","score":0,"priorty":null,"rewatched":null,"notes":null,"private":null,"added_time":"2014-11-13 05:17:34","episodes_watched":12,"chapters_read":null,"volumes_read":null,"hidden_default":null,"custom_lists":[null,null,null,null,null]}
DEBUG 2015-01-23 04:33:21,304 anilist Calling api: https://anilist.co/api/animelist, {'data': {'list_status': 'watching', 'episodes_watched': 14, 'id': 20623}, 'headers': {'Authorization': 'Bearer rtAFj4R7nA6iS8CtAmmY0phkAeQDM0kBQZ5rDvQh'}}
DEBUG 2015-01-23 04:33:23,060 anilist Response: {"list_status":"watching","score":0,"priorty":null,"rewatched":null,"notes":null,"private":null,"added_time":"2014-11-13 05:17:34","episodes_watched":14,"chapters_read":null,"volumes_read":null,"hidden_default":null,"custom_lists":[null,null,null,null,null]}
DEBUG 2015-02-01 07:54:06,070 anilist Calling api: https://anilist.co/api/auth/access_token, {'params': {'refresh_token': 'OTRbssjOe8mcgQMGQnEYlvkLR5IDJNR7VS4NeYgX', 'grant_type': 'refresh_token', 'client_id': 'xxxxxxxxxxxx', 'client_secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}}
DEBUG 2015-02-01 07:54:06,605 anilist Response: {"error":"invalid_request","error_description":"The refresh token is invalid."}
```

My first impression after looking at the previous log snippet an this one, is that the error has something to do with the time difference between the last successfull call to the API and the one that fails to refresh the token. As per the title on this issue, I believe the refresh token seems to be "expiring" for some reason (caching maybe?), which is why it works correctly while the requests are close enough in time, while failing after a certain amount of time passed since the last request made to the API.

**Comment by Josh-Star** [comment]
Ah okay thanks, looks like it was just a config issue on my part. The users that have already had an expired refresh token will need to re-authenticate with your client, but this issue shouldn't happen again from now on.

**Comment by asermax** [comment]
Great! Thanks for taking the time to review this issue :>
