### ISSUE TITLE
API returns Cloudflare DDoS Protection HTML

### ISSUE THREAD

**Issue by ke352802081770314** [Josh-Star/AniList-API-Docs#23]
my JSON parser cannot handle that and shouldn't be expected to.

**Comment by ke352802081770314** [comment]
It seems that my local workstation where I also use a browser to access Anilist web pages is whitelisted by Coudflare for subsequent API access and it works, but on the server where I only use the API and don't browse, I keep getting something like the following. But my API program can neither turn on Javascript not will it handle a redirect, that was not part of the API spec.

<!DOCTYPE HTML> <html lang="en-US"> <head> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" /> <title>Just a moment...</title> <style type="text/css"> html, body {width: 100%; height: 100%; margin: 0; padding: 0;} body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;} h1 {font-size: 1.5em; color: #404040; text-align: center;} p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;} #spinner {margin: 0 auto 30px auto; display: block;} .attribution {margin-top: 20px;} </style> <script type="text/javascript"> //<![CDATA[ (function(){ var a = function() {try{return !!window.addEventListener} catch(e) {return !1} }, b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)}; b(function(){ var a = document.getElementById('cf-content');a.style.display = 'block'; setTimeout(function(){ var t,r,a,f, BTmBvOi={"wuOeY":+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]))}; t = document.createElement('div'); t.innerHTML="<a href='/'>x</a>"; t = t.firstChild.href;r = t.match(/https?:\/\//)[0]; t = t.substr(r.length); t = t.substr(0,t.length-1); a = document.getElementById('jschl-answer'); f = document.getElementById('challenge-form'); ;BTmBvOi.wuOeY-=+((+!![]+[])+(+[]));BTmBvOi.wuOeY-=+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));BTmBvOi.wuOeY+=+((!+[]+!![]+[])+(+[]));BTmBvOi.wuOeY*=+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));BTmBvOi.wuOeY+=!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![];a.value = parseInt(BTmBvOi.wuOeY, 10) + t.length; f.submit(); }, 5850); }, false); })(); //]]> </script> </head> <body> <table width="100%" height="100%" cellpadding="20"> <tr> <td align="center" valign="middle"> <div class="cf-browser-verification cf-im-under-attack"> <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript> <div id="cf-content" style="display:none"> <img id="spinner" src="/cdn-cgi/images/spinner-2013.gif" /> <h1><span data-translate="checking_browser">Checking your browser before accessing</span> anilist.co.</h1> <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p> <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p> </div> <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get"> <input type="hidden" name="jschl_vc" value="c9f6d42c1a4a9cd298ff79da21eb5bf2"/> <input type="hidden" id="jschl-answer" name="jschl_answer"/> </form> </div> <div class="attribution"><a href="http://www.cloudflare.com/" target="_blank" style="font-size: 12px;">DDoS protection by CloudFlare</a></div> </td> </tr> </table> </body> </html>

**Comment by Josh-Star** [comment]
Yeah sorry about this, we should be removing cloudflare pretty soon.

**Comment by ke352802081770314** [comment]
Is there any perspective when it might be removed? 
Or as a workaround, is there any provision that I can whitelist an IP address other than my own (namely of the server my application runs on) from my workstation's browser?

**Comment by Josh-Star** [comment]
Sorry this took so long, cloudflare should now be disabled for good.
