### ISSUE TITLE
invalid API queries result in the Anilist Homepage

### ISSUE THREAD

**Issue by ke352802081770314** [Josh-Star/AniList-API-Docs#24]
Since the API is queried by a program, delivering the Anilist Homepage is not helpful. Instead of lots of HTML a plain text message would be preferable.

**Comment by Josh-Star** [comment]
Invalid requests return a 404 Not Found or other appropriate status codes. I understand that displaying the home page isn't ideal, but the status code should be more then enough for your client to work out if the request was successful or not.

**Comment by ke352802081770314** [comment]
Fair enough. I will check that.
