### ISSUE TITLE
what can be used as {query} in searches?

### ISSUE THREAD

**Issue by ke352802081770314** [Josh-Star/AniList-API-Docs#25]
I can't find an explanation of what can be given as {query} in the documentation.
e.g. GET: anime/search/{query}
can I use wildcards? simple filename wildcards "?" "*" or regexp e.g. ".*" "[abc]" etc.? SQL LIKE-Syntax with "%"? Is it possible to match on specific database fields? 
Will a plain string be taken case-insensitive? Which database field(s) will it be matched against? will it match any substring or only the beginning of that field?
Judging by my tests with GET: studio/search/{query} e.g. "a" seems to match all studios whose title begins with [Aa] (case-insensitive). But I would rather find it documented than guess.

**Comment by Josh-Star** [comment]
The anime/manga searches work a little differently then the rest but for all of them its just plain text, case-insensitive, no like % or regex is supported currently. It should match any substring but this dosen't work too well for the non anime/manga searches at the moment.
For anime/manga the following fields are matched: title romaji, title english, title japanese, and all the synonyms.
For staff/characters first name and last name are matched.

**Comment by ke352802081770314** [comment]
Many thanks for the explanation!
