### ISSUE TITLE
new "main_studio" semantics, or just a database maintenance issue?

### ISSUE THREAD

**Issue by ke352802081770314** [Josh-Star/AniList-API-Docs#28]
I am confused about your labelling of "main studio" in particular for "Pokemon XY" http://anilist.co/anime/19291/PokemonXY where it is set to "Tokyo TV".
According to the Guidelines http://anilist.co/guidelines, "Only one main studio can be added which should be the main anime production studio "
Now I'm sure we agree that TV Tokyo is not the animation producer themselves. Indeed, when I cross-check ANN, http://www.animenewsnetwork.com/encyclopedia/anime.php?id=15491 it credits Animation Production: Oriental Light and Magic, which can be found as "Producers" in your entry, but the label "Producers" is neither mentioned in the guidelines, nor does the API give any basis to pick it from the studio array. 
Has there been a re-definition of the "main studio" semantic, and how can I pick the animation producer from the API data which I used to identify with the "main_studio" flag, as it has been defined originally but may have been superseded - even worse: only for some, not all database entries?

To clarify: I would prefer for main_studio to remain as before (the animation production company) and see the main initiator/money giver/whatever (here: TV Tokyo) flagged with a different new label, if you wish to highlight this now also, instead of redefining the existing label and re-introducing a new one for the old semantics.

**Comment by Josh-Star** [comment]
Yeah this is just a database mistake, Oriental Light and Magic are the main studio for Pokemon XY, I'll fix this now.
