### ISSUE TITLE
Public unread notifications: feature or bug?

### ISSUE THREAD

**Issue by fanalis** [Josh-Star/AniList-API-Docs#29]
Yo. I didn't want to post this on the forums.

Anybody with an access token can see how many unread notifications **any** user has.

```json
{
  "id": 42245,
  "display_name": "KuroiKitsu",
  "anime_time": 0,
  "manga_chap": 0,
  "about": null,
  "list_order": 0,
  "adult_content": false,
  "forum_homepage": null,
  "following": false,
  "image_url_lge": "http://anilist.co/img/dir/user/reg/42245-76UbOGQ0alB5.png",
  "image_url_med": "http://anilist.co/img/dir/user/sml/42245-76UbOGQ0alB5.png",
  "image_url_banner": null,
  "title_language": "romaji",
  "score_type": 4,
  "custom_list_anime": [
    null,
    null,
    null,
    null,
    null
  ],
  "custom_list_manga": [
    null,
    null,
    null,
    "",
    ""
  ],
  "advanced_rating": false,
  "advanced_rating_names": [
    "Story",
    "Characters",
    "Visuals",
    "Audio"
  ],
  "notifications": 0
}
```

Feature or bug?

**Comment by Josh-Star** [comment]
I guess I just kinda forgot about that, I suppose it is a feature, not that I can think of any real use for it on its own. I think it would be a bit of a stretch to call this a privacy issue as its only possible to actually view the notifications when authenticated as the user.

For now I'll leave it for consistences sake, I'll probably remove it when not authenticated whenever we have a big api version bump.

**Comment by fanalis** [comment]
> (...), I suppose it is a feature, not that I can think of any real use for it on its own.

Something similar to WhatsApp "double check".
