### ISSUE TITLE
List score type

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#30]
According to the docs:
0. 10 Point (0-10 int)
1. 100 Point (0-100 int)
2. 5 Star (0-5 int)
3. 3 Smiles (":(",":|",":)" String)
4. 10 Point decimal (0.0 - 10.0 Float)

Dear Josh,

The current way of handling the scores are a complete mess.
Strings, Floats & Integers for updating scores aren't really easy to work with.

It would be really easy if we could see this instead the docs:
0. 10 points => 100 Integer max & 1 Integer min (10x)
1. 100 points => 100 Integer max & 1 Integer min
2. 5 Star => 100 Integer max & 1 Integer min (20x)
3. :) => 100 Integer max & 1 Integer min (just weird)
4. 10 => 100 Integer max & 1 Integer min (10x)

Just 100 - 1 ratings and outputs which are also using this as default would be awesome.

I hope that you consider to add this soon because Atarashii won't be able to support Strings, Floats & Integers at the same time. This will require us an huge amount of time to fix.

**Comment by Kazakuri** [comment]
If it's any help the user model does provide a score_type value so you can know which datatype to expect.
That way if you do want to keep it as a 1-100 system you can simply define a conversion method based off of the user's score_type.

**Comment by ratan12** [comment]
Yes but the Anime general score is using 100-1 while the Anime lists are providing the output based on the animelist.

I am using 10-1 and see 100-1 in the Anime model.

**Comment by Josh-Star** [comment]
I understand the score type are a bit of a pain to work with in a type safe language but I'm having some difficulties understanding why that can't be quite easily be worked around. 

I suppose it would be possible to provide a raw score along with the list item models (we store all the list scores in 0-100 in the database). However when a user changes their score system we do no conversion, e.g. a user is on the 100 point system, a score is 84, they change to the 10 point system, the raw score would still return 84 until they manually change that score using the 10 point system. So its likely you would still require some kind of parsing (or at least rounding) to get the required score for the user's score system. 

My main worry with providing the raw score is that it could encourage API developers to not bother supporting all the score system types, and instead just force the user to use the 100 point system.

**Comment by ratan12** [comment]
We are using https://code.google.com/p/google-gson/ and https://github.com/square/retrofit to take care of the magic with JSON.

The problem with the following libraries is that you can not use multipe variables with the same object name. AniList is providing Strings/Integers/Double with the same object name, this is a pain using the following libraries.

I know that you are trying to force devs to use your score system but this is a bit too much. If you just passed "10.0", "10", "5", "100" & ":)" as string it would be easy to work with.

Currently I decided to drop the ":) :| :(" support because the other are all numbers. Users of AniList won't be able to use the app with this score setting and will in beta 3 get a warning that they won't be able to use the app because the settings.

**Comment by motokochan** [comment]
Beta developers being lazy shouldn't really be a concern of yours. That, or make a different node for each score. You shouldn't switch types on the JSON values unless you really want every score to be treated as the type all of them can fit as, which is "string". Dynamic typing is good and all in some languages, but not all support that. Adding extra burden on developers to figure out how to work with the scores means you'll likely see lots of buggy implementations. Changing the display is easier than changing the entire value handling.

I highly recommend exposing the internal raw score and requesting developers adjust their display based on the user's preferred score type. In the alternate, having "score_numeric" or "score_string" depending on the values would be the next best option.

**Comment by Josh-Star** [comment]
Would the following be a suitable? Or you would rather have some multiplications of them so they are all 0-100, or just give raw score instead?

0. 10 Point (0-10 int)
1. 100 Point (0-100 int)
2. 5 Star (0-5 int)
3. 3 Smiles (0-3 int)
4. 10 Point decimal (0-100 int)

**Comment by motokochan** [comment]
I think just raw 1-100 int would be best. It gives developers a single standard type to count on for communication to _and_ from the API.

It's very easy to convert to and from the display style. For 5 points, divide/multiply by 20. For 10, divide/multiply by 10. The only guidance needed would be the breakpoints for the smile rating and what raw value to submit for a new rating in that type.

**Comment by Josh-Star** [comment]
Okay I've added score_raw to the user list model, will push that in the next few hours and update the docs in the next couple days. You can include score_raw in your post data too and that should work fine.

The breakpoints for the other score systems are rather arbitrary in hindsight, but I'm sure there was some reason for it~

5 Star
- 1 - 1-29
- 2 - 30-49
- 3 - 50-69
- 4 - 70-89
- 5 - 90-100

Smiley
- :( - 1-30
- :| - 31-60
- :) - 61-100

__Make sure to also always floor the scores down, don't just round them normally.__
