### ISSUE TITLE
Multi-Device Support

### ISSUE THREAD

**Issue by motokochan** [Josh-Star/AniList-API-Docs#31]
With the current API setup, you cannot have more than one instance of an API consumer on the same account. Authorizing a second instance changes the refresh token, breaking the first installation.

It might be advisable to add a unique ID field to allow multiple instances of the same client to work properly. It would need to be sent on each request for an access token and during the initial authorization. Although free-form text could be allowed, forcing the unique id to be a UUID would also be an option.

**Comment by Josh-Star** [comment]
Oh yeah never thought about this, okay I've changed some stuff so authorizing another instance with the same user will no longer overwrite the older ones, should allow for multiple devices.

To keep it simple no additional instance id or anything is required, but if we ever get a v2 of the API its definitely something I'd like to support.
