### ISSUE TITLE
Score limit

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#32]
I tried to change the score to 700000 trough the API to check if Atarashii wouldn't crash.

Wasn't disappointed...It became 12.7 out of 10.0 on AniList.
This is an AniList bug because it should be 10.0 like the limit not 12.7 while I changed it into 700000

Ayway here is the proof http://anilist.co/animelist/Ratan12

**Comment by Josh-Star** [comment]
Thanks, the fix for this will push in a couple hours.
