### ISSUE TITLE
Returning object instead of Array

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#34]
My mangalist is empty causing the API to return an object instead an empty array.

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 202 path $.lists
```

**Comment by Josh-Star** [comment]
Hey, just want to confirm if the title for this is incorrect? Usually lists would return an object but seem to be returning an array when empty.

**Comment by ratan12** [comment]
ah yes my bad, the title is wrong.

**Comment by Josh-Star** [comment]
Sorry this took so long, should be fixed now.
