### ISSUE TITLE
Characters API not returning Voice Actors

### ISSUE THREAD

**Issue by Offearmed1958** [Josh-Star/AniList-API-Docs#35]
Hey Josh, I was fetching some characters from the api but seems the api doesn't supply voice actors can you please include it???

**Comment by Josh-Star** [comment]
character/{id}/page should return staff with anime & manga, and voice actors with anime and manga. Are you querying character/{id} by accident or is character/{id}/page not working properly?

**Comment by Offearmed1958** [comment]
oh, sorry about that, looks like i was fetching characters whose va wasn't set yet anyway you can include when the api data was last updated?

**Comment by Josh-Star** [comment]
The API data is the exact same data as the usual AniList data, we don't keep track of the update times for character relations as its a little pointless; its either there or its not. 

If we're missing something and you need it included in the API data it would be very helpful if you could submit the data to our mods so they can get it added: http://anilist.co/guidelines
