### ISSUE TITLE
Score reset bug

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#36]
If you change th score system to the smileys it will break all scores in the API and when you switch back (To the 10 system) all the scores are removed ^^

I lost all my anime scores now. Long live my backup!

**Comment by Josh-Star** [comment]
I can't seem to reproduce this, could you elaborate on what by the "break all the scores", is it just returning them as 0?

**Comment by ratan12** [comment]
Yeah I had the decimal point system. I switched to the smiley system and made an animelist request with the API. All scores were 0 but on the site they were converted right to smileys. then I switched to the 5 star rating which changed everything into 0 on the website and API.

**Comment by Josh-Star** [comment]
I've tried a fair few times now and can not reproduce this at all. Can you reproduce this or is it possibly an issue with Atarashii? Are you using the new score_raw or just the normal scores?
