### ISSUE TITLE
Reviews & import?

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#37]
Is there any Review or import API url?

**Comment by Josh-Star** [comment]
Yep I thought I updated the docs with the review information but I guess I didn't, so I will add them in the next few fays, the routes are the same as the anilist web site so you can have a quick look there if you need them. 

For import I assume you mean list import, its not something we officially support but it is available via the api #12

**Comment by ratan12** [comment]
@Josh-Star is there also a raw score available?

**Comment by Josh-Star** [comment]
[Review documentation is now up.](http://anilist-api.readthedocs.org/en/latest/reviews.html) 
Reviews only use a 0-100 int for their score so no need for raw scores.

**Comment by ratan12** [comment]
I did not saw anything related with pages in the docs. So is the review request returning all the reviews of an anime or a manga?

**Comment by Josh-Star** [comment]
Yep, at this point we're not really expecting to get any large number of reviews for a series so it will just return all of them.

**Comment by ratan12** [comment]
Okay thanks ^^
