### ISSUE TITLE
Anime/Manga Search doesn't consider 18+ Content on API

### ISSUE THREAD

**Issue by Lebleus** [Josh-Star/AniList-API-Docs#40]
Hello again,

On the API, the Anime/Manga Search doesn't consider if the authenticated user has "18+ Content" enabled or not.

You can try by searching "Bible" on Animes with the API.

**Comment by Josh-Star** [comment]
At the moment non of the our returns will filter out 18+ content, regardless of whether the user has enabled them or not. This will probably change in a future API version, but for now its something you need to manage in your application.
