### ISSUE TITLE
Date format inconsistency

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#41]
The reviews docs says enough "2014-05-03 14:44:15".

You are using everywhere ISO8601 except in the reviews. I can not see which timezone it is ^^
"2014-05-03 14:44:15" to "2014-05-03T14:44:15+09:00" please?

**Comment by Josh-Star** [comment]
Sorry this took so long to get too, exam and stuff~ 
Should be fixed now, I'll update the docs shortly.
