### ISSUE TITLE
Pin Authorization Lifetime

### ISSUE THREAD

**Issue by Zinshis** [Josh-Star/AniList-API-Docs#42]
I've been utilizing the pin authorization and was wondering what the lifecycle is of the pin that gets granted? Currently I'm storing the pin the user returns to my application in a backend database in an encrypted format. After trying to use this stored pin the next day the api returned with an error when I attempted getting an access token.
Is the pin supposed to reset daily, or are there ways to persist the pin for a user?
Or is the pin meant to be used once initially, and after that the refresh token needs to be used for reacquiring an access token?

**Comment by Josh-Star** [comment]
The pin only has a life time of 1 hour. The pin is meant to be used once initially, and after that the refresh token needs to be used for reacquiring an access token.
