### ISSUE TITLE
browse/anime full_page

### ISSUE THREAD

**Issue by Kuraperunat** [Josh-Star/AniList-API-Docs#43]
Trying to get browse/anime titles with parameters "status" = "Currently Airing" and "full_page" = "true" doesn't seem to ignore pagination.

e.g. https://anilist.co/api/browse/anime?full_page=true&access_token=...&status=Currently+Airing
returns 40 titles. I've tried few different parameter combinations yet I haven't been able to get full_page working.

Am I just failing something or...?

**Comment by Josh-Star** [comment]
Sorry this took awhile, a rather silly mistake on my part, I wrote it in the docs as full_page but it was actually just fullpage, anyway it supports both now and should work as expected.
