### ISSUE TITLE
AnimeList entry deletion returns 500

### ISSUE THREAD

**Issue by danejur** [Josh-Star/AniList-API-Docs#45]
I may be executing this request incorrectly, but it appears that when this request is sent with the DELETE verb, it returns a 500. Is that the correct placement of the AnimeID? When I attempt to call this on an ID that is located on my "completed" list (verified by executing the same command with a GET), it returns XML in the shape of a server exception message.

The request in question:
http://anilist.co/api/animelist/1?access_token=$ACCESS_TOKEN

**Comment by Kazakuri** [comment]
Make sure you are including the appropriate Authorization header in your request.

>Now to access the resource server on the resource owner’s behalf, simply include the following header with all your requests

>Authorization: Bearer access_token

**Comment by danejur** [comment]
I'm fairly certain the request is well formed. I use the same authentication Megan's
method for everything else, and that all work fine.

Note that I'm not getting an unauthorized response. I'm getting a 500 in the form of a page redirect (the response is an html document, not JSON)

**Comment by Kazakuri** [comment]
Yeah, you're getting the "Woops, looks like something went wrong" error, right?
![error](http://i.imgur.com/ziU4SHQ.png)

I only get that if I don't include the header or the item wasn't on my list in the first place.
![header](http://i.imgur.com/k1nlxk2.png)

**Comment by danejur** [comment]
That is absolutely bizarre. I was absolutely certain that it was well-formed, but lo-and-behold, it was missing the capital B. Oh well, thanks Kaz.
