### ISSUE TITLE
Manga search not returning what should be an obvious result

### ISSUE THREAD

**Issue by Nihilate** [Josh-Star/AniList-API-Docs#49]
The response when searching for "Kingdom" using the manga search doesn't contain the [Kingdom](https://anilist.co/manga/16765/Kingdom) manga series. Given that the name matches the search text exactly it seems odd that it doesn't.

Assuming it's a quirk of the search algorithm is there a way around this?

**Comment by Josh-Star** [comment]
Sorry about that, I've updated the anime & manga search to include an extra query that will find an exact title match, first for romaji, and then for english if no romaji match if found. If there is an exact match (case insensitive) it will prepend it to the start of the return array. 

[Kingdom now returns first for both the anime and manga search.](http://anilist.co/search?q=kingdom)

**Comment by Nihilate** [comment]
Awesome, thanks a ton.
