### ISSUE TITLE
Filter anime by "Tragedy" genre does not work.

### ISSUE THREAD

**Issue by EgorDm** [Josh-Star/AniList-API-Docs#51]
Hello,

Everytime I try to filter anime by tragedy genre I get page which says "Whoops, looks like something went wrong.".

How to reproduce:
1: I took the list with all genres from here "https://anilist.co/api/genre_list?access_token=myaccestoken"
2: I added "Tragedy" genre form the list to the filter and I got this url "https://anilist.co/api/browse/anime?access_token=myaccestoken&genres=Tragedy" which gives me this error.

A screenshot to error message :p
http://prntscr.com/89lfiq

**Comment by Josh-Star** [comment]
Ah yeah Tragedy seems to be a manga only genre so its throwing a error for anime when there aren't any results to get. I'll push the fix for this in a little bit.

**Comment by EgorDm** [comment]
Ah, alright thanks :)

**Comment by Josh-Star** [comment]
This should be fixed now. We also did a a bit of genre clean up and removed some genres that were never used or at least never used correctly, that included the Tragedy genre.
