### ISSUE TITLE
Synonyms character type?

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#54]
Are synonyms always in English?

**Comment by Josh-Star** [comment]
Synonyms are a mix of Japanese, Romaji and English titles, often the Japanese/Romaji synonyms will also include English characters.

We don't currently have any indication for which language each synonym is in, and I doubt we ever will as 1. the back log and 2. often the language for synonyms isn't as clear cut as just this language or that language.

Hope this answers your question.

**Comment by ratan12** [comment]
yup, thanks!
