### ISSUE TITLE
Response returned Anime Model with no "classification" value?

### ISSUE THREAD

**Issue by kuchienkz** [Josh-Star/AniList-API-Docs#55]
Im using C#, Here is my code:.
>HttpWebRequest Req = HttpWebRequest.CreateHttp("https://anilist.co/api/anime/" + AnimeID + "/?access_token=" + AuthAccessToken);
> Req.ContentType = "application/x-www-form-urlencoded";
            Req.Headers["Authorization"] = "Bearer " + AuthAccessToken;
            Req.Method = "GET";

>Stream objStr = Req.GetResponse().GetResponseStream();
>StreamReader objRdr = new StreamReader(objStr);

> string responseJSON = objRdr.ReadToEnd();

responseJSON:
> {"id":20729,"title_romaji":"World Trigger","type":"TV","image_url_med":"http:\/\/anilist.co\/img\/dir\/anime\/med\/20729.jpg","image_url_sml":"http:\/\/anilist.co\/img\/dir\/anime\/sml\/20729.jpg","start_date":"2014-10-05T00:00:00+09:00","end_date":"2015-10-03T00:00:00+09:00","classification":"","hashtag":"#\u30c8\u30ea\u30ac\u30fc\u30aa\u30f3","source":"Manga","adult":false,"popularity":3017,"title_japanese":"\u30ef\u30fc\u30eb\u30c9\u30c8\u30ea\u30ac\u30fc","title_english":"World Trigger","synonyms":[],"description":"One day, a gate to another world suddenly opens in Mikado City. Aliens invincible to Earth\u2019s weapons, called \u201cNeighbors\u201d, start coming over. Earth\u2019s only line of defense is a mysterious group called the \u201cBorder\u201d who are armed with weapons called \u201cTriggers\u201d.<br>\r\n <br>\r\nFour years later, the city has recovered from initial attacks and citizens of Mikado City have started to get use to the Neighbor\u2019s attacks. Yuma Kuga, a transfer student, and his classmate Osamu Mikumo find themselves fighting a Neighbor that suddenly appears. Osamu, who is actually a Border agent, activates his Trigger but is unable to defeat it. This leaves Yuma to activate his own Trigger and defeat the alien. Yuma reveals that he is not part of Border and is actually a Neighbor who has transferred from the other side.<br>\r\n<br>\r\n(Source: Crunchyroll)","image_url_lge":"http:\/\/anilist.co\/img\/dir\/anime\/reg\/20729.jpg","image_url_banner":null,"duration":23,"airing_status":"finished airing","average_score":"67.7","total_episodes":48,"youtube_id":"2oui7JLlBpk","relation_type":null,"role":null,"list_stats":{"plan_to_watch":717,"watching":1257,"completed":290,"on_hold":232,"dropped":521},"genres":["Action","School","Sci-Fi"],"airing":null}

As you can see, ("classification":"") means "classification" = "" (empty string).
Tried other animes. Am i do something wrong?

**Comment by Josh-Star** [comment]
I'm afraid we no longer keep track of classifications, its still in the API for legacies sake (some old anime do have it) but will likely be completely removed in the next major API version. It should really be returning a null, and not an empty string but thats a minor issue so I'll probably just leave it for now.
