### ISSUE TITLE
Querying for a non-existing anime times out

### ISSUE THREAD

**Issue by sotojuan** [Josh-Star/AniList-API-Docs#56]
Currently, if you query for an anime that doesn't exist (say `anime/3`), the request actually never "ends". Instead it times out.

This is fine in the sense that adding a time out handler isn't hard for us developers, but it would be much friendlier if it gave a 404 status.

**Comment by Josh-Star** [comment]
I'll look into this when I get home later, but from what I remember and can see in the chrome dev console it should just end and return a 410 Gone response error.

**Comment by sotojuan** [comment]
I'll give it a try later, maybe it was just the client I was using. Thanks.

**Comment by sotojuan** [comment]
Yeah it was an issue on my end. The API returns 410 as it should!
