### ISSUE TITLE
405 method not allowed error

### ISSUE THREAD

**Issue by lamiajoyee** [Josh-Star/AniList-API-Docs#58]
Hello I am trying to make a request with client credentials but receiving this 405. I am using c# and my URL looks like this--

https://anilist.co/api/auth/access_token?grant_type=client_credentials&client_id=lamiaxxxxxx&client_secret=abcdefghijkl12345 

Please give me some guidance. Confused

**Comment by Kazakuri** [comment]
Looks like you're using a GET request, but auth/access_token requires a POST request

```
POST: auth/access_token

Url Parms:
grant_type    : "client_credentials"
client_id     :  Client id
client_secret :  Client secret
```

**Comment by lamiajoyee** [comment]
thank you
