### ISSUE TITLE
What does "adult" key actually do?

### ISSUE THREAD

**Issue by sgript** [Josh-Star/AniList-API-Docs#60]
Hi there,

I was wondering which anime is actually filtered as **adult**?
We currently have an app that makes use of Anilist's API and were wondering what this key/value pair means, so we could do some filtering for some inappropriate content.

Thanks.

**Comment by Josh-Star** [comment]
Adult is a boolean for hentai (porn). You may want to do some additional filtering shows with the Ecchi genre too but I would think most of them are fine.
