### ISSUE TITLE
Access resources only as resource owner?

### ISSUE THREAD

**Issue by MasterBugPatch** [Josh-Star/AniList-API-Docs#66]
So let's say I just want to get the character names of an anime and that there is no need at all to involve any clients in this, I just want to get the character names, as the API key holder. 

So I see you guys in the docs say that if I need to do so just use "Authorization: Bearer access_token". But in order to get this access token I need to do post to "auth/access_token" every hour for the access token. Why do I need to do this if I'm only accessing as the resource owner, is there not any way for me to just obtain the character names by using the Client ID and Client Secret?

If no other way, would I have to to obtain a new access token every hour..? Could I just get the access token every time I need to do a request because I wouldn't be sure how to create a system that get's a new access_token every hour without having to put checks of time in the PHP scripts.

**Comment by Kazakuri** [comment]
Your PHP script is a client so it needs to use its' client id and client secret to get the access token (the API key, if you will) to access API endpoints.
The access token idea is not new to AniList but is a standard of OAuth, so if you want to know more you can research into that. There's some good reasons supporting access tokens [here](http://stackoverflow.com/questions/7030694/oauth2-why-do-access-tokens-expire)

You do not need to obtain a new access token as soon as the old one expires, nor do you do you need to wait for your current access token to expire before requesting a new one.
Ideally you'd want to store the `access_token` and `expires` values on the server (file_put_contents / file_get_contents, local database, etc) then start out each script like this:

```php
if ($expires < time()) {
  $access_token = get_new_token();
} else {
  $access_token = get_current_token();
}
```

**Comment by MasterBugPatch** [comment]
@Kazakuri I thought I might have to do that, it just seemed really inconvenient to have to have code that checks the expiration of the access token every time I use it.

**Comment by Josh-Star** [comment]
Kazakuri has pretty much said everything that needs to be said so I'll close this.

I'm afraid it is all standard oAuth and I have no plans on changing it. I don't really see the expiry check as all that big of an inconvenience, and you could alternatively run an hourly cron-job if you don't wan't to worry about it on every request. There are also plenty of oAuth client packages out there that should handle all of the oAuth stuff for you.
