### ISSUE TITLE
Confused: anime_time format?

### ISSUE THREAD

**Issue by kuchienkz** [Josh-Star/AniList-API-Docs#67]
....................................................
"id": 1,
"display_name": "Josh",
 "anime_time": 54067,
"manga_chap": 587,
.....................................................

What is the time format of "anime_time" value? Unix Timestamp? I can't figure it out :(
When i opened your user page (http://anilist.co/user/1) it was 46.8 days. How can 54067 become 46.8 days ???

**Comment by Kazakuri** [comment]
`anime_time` is in minutes. That should be make a bit more clear since the documentation doesn't stay up to date with what Josh watches or anything.
54,067 / 60 (minutes) / 24 (hours) = 37.55 days

**Comment by kuchienkz** [comment]
lol how foolish i am! thanks for the fast reply :D
