### ISSUE TITLE
API's search feature doesn't handle Japanese

### ISSUE THREAD

**Issue by IllDepence** [Josh-Star/AniList-API-Docs#9]
It whould be nice to be able to search for anime using parts of their real title.

A request like
`https://anilist.co/api/anime/search/月刊?access_token=w1x257Q1gWTPCUSxQqXb...`
or rather (url encoded)
`https://anilist.co/api/anime/search/%E6%9C%88%E5%88%8A?access_token=w1x257Q1gWTPCUSxQqXb...`
yields no results.

Whereas
`https://anilist.co/api/anime/search/gekkan?access_token=w1x257Q1gWTPCUSxQqXb...`
does.

**Comment by Josh-Star** [comment]
Anime/Manga search now supports Japanese characters.

**Comment by IllDepence** [comment]
awesome! :3
